[versions]
coreKtx = "1.12.0"
gradle = "8.2.1"
kotlinGradlePlugin = "1.8.0"
lifecycle = "2.7.0"
desugaring = "2.0.4"
annotation = "1.7.1"
legacySupport = "1.0.0"
appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"
apacheCommons = "3.12.0"
guava = "31.0.1-jre"
webkit = "1.9.0"
media = "1.7.0"
viewbinding = "8.2.1"
browser = "1.7.0"
exoplayer = "2.19.1"
swipeRefreshLayout = "1.7.2.4"
retrofit = "2.9.0"
kotlinxSerialization = "1.4.1"
kotlinxRetrofit = "0.8.0"

[libraries]
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinGradlePlugin" }

lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-legacySupport = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupport" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "media" }
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
apache-commons = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommons" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
viewbinding = { group = "com.android.databinding", name = "viewbinding", version.ref = "viewbinding" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }

# ExoPlayer
exoplayerCore = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
exoplayerUI = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
extensionMediasession = { module = "com.google.android.exoplayer:extension-mediasession", version.ref = "exoplayer" }

# SmoothRefreshLayout
srlCore = { group = "com.github.dkzwm", name = 'srl-core', version.ref = "swipeRefreshLayout" }
srlExtClassics = { group = "com.github.dkzwm", name = 'srl-ext-classics', version.ref = "swipeRefreshLayout" }
srlExtMaterial = { group = "com.github.dkzwm", name = 'srl-ext-material', version.ref = "swipeRefreshLayout" }
srlExtDynamicRebound = { group = "com.github.dkzwm", name = 'srl-ext-dynamic-rebound', version.ref = "swipeRefreshLayout" }
srlExtHorizontal = { group = "com.github.dkzwm", name = 'srl-ext-horizontal', version.ref = "swipeRefreshLayout" }
srlExtTwoLevel = { group = "com.github.dkzwm", name = 'srl-ext-two-level', version.ref = "swipeRefreshLayout" }
srlExtUtil = { group = "com.github.dkzwm", name = 'srl-ext-util', version.ref = "swipeRefreshLayout" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
kotlinxSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxRetrofit = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinxRetrofit" }